### ISSUE TITLE
The result

### ISSUE THREAD

**Issue by mghifariyusuf** [MaxGraey/react-native-console-time-polyfill#2]
Where the result will show? In terminal console?
I used it for my android app. How to show it as text in alert? Thanks ^^

**Comment by MaxGraey** [comment]
Hi **mghifariy**,
`react-native-console-time-polyfill` created only for debug purposes, so you should use it in emulator which has terminal output. However, you can also debug on a real device [using remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/)

**Comment by mghifariyusuf** [comment]
No problem, I have modified the code for return the result and show it up in alert window ^^

**Comment by MaxGraey** [comment]
Perfect, so I'll close this. You could reopen this in future.
