### ISSUE TITLE
Bundling error

### ISSUE THREAD

**Issue by spotsadmin** [MaxGraey/react-native-console-time-polyfill#3]
I am getting this error in the packager. Any idea how to fix it? This package used to work for me. The error started after moving to react-native v0.56.

```
error: bundling failed: Error: While resolving module `react-native/Libraries/Performance/RCTRenderingPerf`, the Haste package `react-native` was found. However the module `Libraries/Performance/RCTRenderingPerf` could not be found within the package.
```

**Comment by MaxGraey** [comment]
Thanks for report. I created PR for that. Could you try it? Just install as `npm install github:MaxGraey/react-native-console-time-polyfill#fix-react-56`
