### ISSUE TITLE
Cannot add new property 'time'

### ISSUE THREAD

**Issue by efstathiosntonas** [MaxGraey/react-native-console-time-polyfill#9]
On react-native `0.71.3` (hermes enabled) it throws this:

![Simulator Screen Shot - iPhone 14 Pro - 2023-03-03 at 11 46 37](https://user-images.githubusercontent.com/717975/222688002-dfacc0de-b585-497f-8718-5dbe815b2b1d.png)

I'm using:
`"react-native-console-time-polyfill": "^1.2.3"`

**Comment by MaxGraey** [comment]
Hi, I haven't used ReactNative for a while. So if you know how to fix it, I would be happy to approve PR from you

**Comment by efstathiosntonas** [comment]
Hi Max, I have no clue why this is happening, I've just upgraded from `0.68.x` to `0.71.3`. There are lots of changes between these versions and I'm kinda lost, don't know what might have changed in between.

When I find some free time I'll look into it. To me it seems that `console` is frozen and nothing can be added into it.

**Comment by efstathiosntonas** [comment]
Hey Max, closing this as it seems it works on 0.71.6.
